services:
  - type: web
    # এটি ডিফল্ট নাম হিসেবে থাকবে, তবে ইউজার চাইলে পরিবর্তন করতে পারবে
    name: bdfolio
    runtime: static
    buildCommand: npm install && npm run build
    publishPath: ./dist
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        from: /*
        to: /index.html
